language: python
services:
  - docker
before_script:
  - docker build -t andrumdev/rumplenator:$TRAVIS_COMMIT .
script:
  - docker run --env-file .test.env andrumdev/rumplenator:$TRAVIS_COMMIT python -m pytest -s
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
# before_deploy:
#   - cp .prod.env .env
deploy:
  # use v2: https://docs.travis-ci.com/user/deployment-v2
  edge: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: eu-central-1
  app: rumplenator
  env: andrumpleteazer-rumplenator
  bucket: rumplenator-source
  on:
    branch: tgoodall/dockerize # testing, change this to main
