language: python
python:
  - "3.8"
env:
  global:
    - TMI_TOKEN=token
    - CLIENT_ID=client_id
    - BOT_NICK=rumplenator
    - BOT_PREFIX=!
    - CHANNEL=travis-test
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest -s
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
  