language: python
python:
  - "3.8"
env:
  global:
    - TMI_TOKEN=token
    - CLIENT_ID=client_id
    - BOT_NICK=rumplenator
    - BOT_PREFIX=!
    - CHANNEL=travis-test
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest
