language: python
python:
  - "3.9.1"
services:
  - docker
before_script:
  - docker build -t andrumdev/rumplenator:$TRAVIS_COMMIT .
script:
  - docker run --env-file .test.env andrumdev/rumplenator:$TRAVIS_COMMIT python -m pytest -s
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
