language: python
services:
  - docker
before_script:
  - docker build -t andrumdev/rumplenator:$TRAVIS_COMMIT .
script:
  - docker run --env-file .test.env andrumdev/rumplenator:$TRAVIS_COMMIT python -m pytest -s
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: gYa9dZIvr0jf6xmyEPc7v4qvALO/t6gVy2LqbjDk2irAs89/Ov4H1I9s/o1ZQ+30pvNkNZTeg88UeR5joe9Wvfn4L6iqBTkywOGapDzG7jupzHCYFth02MeQEkGaSD/jup0RczOo27oWAnnzRPReK/7w5ADCgtM5mIH8xHljGGweR8EatT46K596KdaUhu+Rf338nTrfLEAA+ov7g8RNFmD7kz0thX8a6qU+0G+KIKhH1y4EK3cKApoesrwEVaLgoUxaja/c8aLgjQ58O/5eryKZe3qYmFaN6StVTmplvK9clfPDevGzlBtl1Uyluq3iV7X9EP5Kudab18ESxyzt7qoXwuMMGx/WQ8DgaS2y3N3TgBs+C7OuHEbwlGBDJ3ryS1NzSphJq05BOFP/HR1Tp94lhU/q5tkY47XgkWkcQwgqEil7thXXR6RNpsRQRh2UjsI93bKOagnQZQmkQOdgPrnANiDXEBY0juFcsX4keuJzbbqfvO1gw98JTNG0hMIrGExhow+TJERSgPO8GyGXPRF/GcR0M9kyHgjl6HnMuhd1oGYeLv9eXa2gHjIh1l+ATybWkkpOMRRaq8EFWgkwyJrE33jOgV3iaMxr54XldKrKBlK+cng4o8n/y5VG1kh6onq1LzrHKFmLXZfodfZ8bPlA9+R9yDQpnxuPO1iHqRE=
  secret_access_key:
    secure: nYi7mMSfWkr1C4zA/i2SyaaGuYo15kDV3lSjITOeZ2ESa7sbedaPGWWhInvi4BsiGxkDMQGGQoWhjsAWAJDJd285jhWBBBi5JLO2YDDXxPUduqb2Jq5I5xqVk0medkL7CXN4A5tBW4iL2v9bJo3ZKQb2i2M9FVGXdGFw4Hxojo6y2hGmSy/X1DhgmKMNaE2AEuAsXKYR8cKN13Vwdytts2Ee1kNGtYyKdiW8S/64lHqOjKI1QFnL+9JonoYe5SJzkXdaOUtG4mzDnsTjz7wOLK6jM+VN2Q4QQpgtUm/+Ga7SCIWTOjq0lyAHayFeYyjjHy9ODPMtvbsQbosfGJuljs9Msg5XmLJmUkN7/on3oWUTYJzy3SJMdv4CP6/k3SXm8gYaMeeZtOpcudwLS82E4++X5MjPr5Ex6k0/M33+gnECux16Qd4N6uacqUfhFqwARCVDBZcmMt6gTC74kyRATzRLC9Nf9mQUCrlYFiFwCMXv6NZTR4ZxAMcGqd5ZZJ517dPmWu1pQrr2FYVSq8RUiwknWntv42UmAUneX/4rTDh55qxLTKZ+HOGnb/V2wAqTveLkt3mruR0vAw9DkTJ9qe42Yw+J712nsV0ScVkLiVxtsHTbXoYb6C66LoyQGXafKyb6ghMpWxW0zDsRHIpe+QUbG5Gs5XW8byIxJXQ8Dec=
  region: eu-central-1
  app: rumplenator
  bucket: andrumdev-rumplenator-bucket
  on:
    branch: tgoodall/dockerize # testing, change this to main
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
