language: python
services:
  - docker
before_script:
  - docker build -t andrumdev/rumplenator:$TRAVIS_COMMIT .
script:
  - docker run --env-file .test.env andrumdev/rumplenator:$TRAVIS_COMMIT python -m pytest -s
deploy:
  provider: elasticbeanstalk
  # access_key_id:
  #   secure: K736AqupB9QcR/zKtyYB6kSUxhhdtVk+WQYlZKY5+n/206lM2Dtnu2hF+vd+XY+MkTsK0xKteGEwTTfnCmCISU/EKge00rY116fU/IlkdWQ0+NISI/F8xH2tSG5UBGLIt58Ug/xNSFBwQau9/FGAof230r2/Y2r5H5+I3ADrQrijgn05YVozQsY5natLTFfrFSK9jOv5SPsPStSGCUUcHmTxGQe2NvHXsA5F5cWmUVvggkFHQqw9sr40WvbO4Ua3XiDSn2B8ktirHWtV48DEtbD3Pzg7E2U/ejWX4/RQCKoSInGHBIIRj0TbFXUpLDxXTOZnIAvWCz3Z6/UcsdZ1gdLa1gkjENfSt8EltY1VBO8AdLI4WtwWYhy9hQN0sC8npwMZNF4DDNANHr7CLfYwQJXlbp8AMCJXhd6h25a8VDxjFfA+vpygcvqG/fl6bhKUgNOlzFRGrQuoDHP5tv+vTKsNQQ/Lo2SGXsfdi9y4Ul6YXcM1SfDsdEaTUE6/NYa+S3VxlZAsc6lt3PpKyh6vHSXrLRFv1MXV8brqy+W2wZWDDbfFH/I3iAGiUqKYI6JImjmJIA1xE6k5UoSiQdHwcDMdizIcXDQaXADj0j+dCnhdbB3snVu3Uc2WhDGeEUye0ffU7x9VXtKavJgOF6nL1QISj3iQyeqLALMQPZo2SDI=
  # secret_access_key:
  #   secure: nYi7mMSfWkr1C4zA/i2SyaaGuYo15kDV3lSjITOeZ2ESa7sbedaPGWWhInvi4BsiGxkDMQGGQoWhjsAWAJDJd285jhWBBBi5JLO2YDDXxPUduqb2Jq5I5xqVk0medkL7CXN4A5tBW4iL2v9bJo3ZKQb2i2M9FVGXdGFw4Hxojo6y2hGmSy/X1DhgmKMNaE2AEuAsXKYR8cKN13Vwdytts2Ee1kNGtYyKdiW8S/64lHqOjKI1QFnL+9JonoYe5SJzkXdaOUtG4mzDnsTjz7wOLK6jM+VN2Q4QQpgtUm/+Ga7SCIWTOjq0lyAHayFeYyjjHy9ODPMtvbsQbosfGJuljs9Msg5XmLJmUkN7/on3oWUTYJzy3SJMdv4CP6/k3SXm8gYaMeeZtOpcudwLS82E4++X5MjPr5Ex6k0/M33+gnECux16Qd4N6uacqUfhFqwARCVDBZcmMt6gTC74kyRATzRLC9Nf9mQUCrlYFiFwCMXv6NZTR4ZxAMcGqd5ZZJ517dPmWu1pQrr2FYVSq8RUiwknWntv42UmAUneX/4rTDh55qxLTKZ+HOGnb/V2wAqTveLkt3mruR0vAw9DkTJ9qe42Yw+J712nsV0ScVkLiVxtsHTbXoYb6C66LoyQGXafKyb6ghMpWxW0zDsRHIpe+QUbG5Gs5XW8byIxJXQ8Dec=
  region: eu-central-1
  app: rumplenator
  bucket: andrumdev-rumplenator-bucket
  on:
    branch: tgoodall/dockerize # testing, change this to main
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
